### PR TITLE
fixed #263 better settings documentation

### LINKED ISSUE #263: Better documentation of user settings
The settings page has a growing number of options. These are not documented at all. There are various paths that must be set where it's not clear what the path should be

At a minimum, these options should be explained in the manual. I'd also like for the path-based stuff to go from text box to file browser dialog.

### PR DESCRIPTION
**Pull request by lausdahl**
I added a help button and text for most of the settings that I know what are, and deleted one setting about coe debug that was no longer referenced.

### CODE REVIEW

**Comment by ldcouto** [comment]
Looks really good, but there's some weird object object setting at the end.

I think this is something in the underlying settings and not the help renderer

untitled

**Comment by lausdahl** [comment]
ok I fixed the wired object it happened to be the help message map

**Comment by bandurvp** [comment]
@ldcouto I've pushed some changes to this branch and it looks like they're automatically included in this pull request.  Is this correct?

**Comment by ldcouto** [comment]
Ya, that's how it goes.

**Comment by ldcouto** [comment]
This looks really good now. A LOT better than the previous releases.

Some of the settings documentations are a little basic, but I think they can be updated in the future if we get user feedback.

**Pull request merged**
