### PR TITLE
Ctha/bootstrap

### PR DESCRIPTION
**Pull request by CThuleHansen**
Hi Luis,
If you have time, I would like you to quickly run through it and possibly build it.

Don't worry, I will not make this whole "you checking my stuff" into routine. It is only because I have made a lot of configuration that would ruin everyone's experience if it does not work.

I have updated the readme as well with new instructions.

This branch also contains the typings branch.

### CODE REVIEW

**Comment by ldcouto** [comment]
This builds and runs successfully for me. A lot of lint errors though (speaking of which, should we add a regular JS lint?).

I also think we have too many package managers now. Let's add gulp tasks for bower and typings. At least the installs.

**Comment by CThuleHansen** [comment]
Hi Luis,
I will create some gulp tasks to install bower and typings.
Yes, I turned lint on. However, the mistakes are "simple" to fix. I will remove it from the default build task

**Comment by ldcouto** [comment]
Yeah, you're probably right. But we should keep it in mind in case someone does decide to use regular JS.

**Comment by CThuleHansen** [comment]
Ahh yes. Good point! I agree.
I have created an init task and removed lint from the build task.

**Comment by CThuleHansen** [comment]
That should do it.
Ready for merge.

**Comment by ldcouto** [comment]
I don't love having a gulp task that installs global stuff.

There are gulp plugins for typings and bower. Can we use those instead  of the shell plugin?

**Comment by ldcouto** [comment]
I will branch off and add those tasks

**Comment by ldcouto** [comment]
See #5

**Pull request closed without merging**
