### PR TITLE
Traceability of mm create/modify, coe create/modify and simulation

### PR DESCRIPTION
**Pull request by lausdahl**
This adds the typings stuff and traceability for the app

### CODE REVIEW

**Comment by ldcouto** [comment]
Is there a chance we can do a full migration to types2 as part of this?

**Comment by CThuleHansen** [comment]
Not sure what you mean? Can you elaborate?

**Comment by ldcouto** [comment]
Isn't there a bunch of typings definitions left?

I'd like to do a complete migration. But maybe it makes sense to open a new branch for that?

**Comment by CThuleHansen** [comment]
It would be really great to get this in first, so it will not be a impossible commit because of too many changes. So I vote for a new branch. Only ones remaining are w2ui, sql.js, ace and jquery.

**Comment by ldcouto** [comment]
Yeah, alright. Let's do it. Let's just not drop this effort.

**Comment by CThuleHansen** [comment]
So i'll merge it? Right?

**Comment by ldcouto** [comment]
Yep

**Pull request merged**
