### PR TITLE
Enabling support for COE 0.2.14 (new release) this enabled a FMU max step size constraint

### PR DESCRIPTION
**Pull request by lausdahl**
This pull request should only be accepted after #276.

It adds a new FMU max step size constraint which is required by COE 0.2.14 to keep the same behaviour. The constraint for max step size is no longer active by default and behaves now like the other constraints. This UI update enabled the user to add it in the configurations.

Please merge once `master` is open again.

### CODE REVIEW

**Comment by ldcouto** [comment]
Does this require the COE 0.2.14 to work or is it backwards compatible?

**Comment by ldcouto** [comment]
This doesn't seem to work. I just get a an empty box.

image

**Comment by lausdahl** [comment]
It is as intended there is not config for the constraint

**Comment by lausdahl** [comment]
COE 0.2.14 works with previous configs but it will not take fmu max step size into account unless asked to do so by the constraint. Previous version of the COE has this enabled by default but it was not described in the documentation. Now the documentation is up to date with the implementation and the user must manually add the constraint.

Note adding the constraint is not compatible with old COE versions

**Comment by CThuleHansen** [comment]
Fixed the issue reporting by Luis

**Comment by ldcouto** [comment]
Tweaked display message. Good to go.

**Comment by ldcouto** [comment]
Tweaked message. Good to go.

**Pull request merged**
