### PR TITLE
Projdom

### PR DESCRIPTION
**Pull request by ldcouto**
Hey Keneth,

The project DOM stuff is up.

We have: 
* a container class for generic files we don't really care about.
* a config class for configurations that we care about. It's a key,value pair of strings. I'd like us to find a smart way to support multi-typed configuration values but it does not look super easy.
* a conmap class for connections mappings. I gave this one a dedicated class since connection mappings are always the same so we can take advantage of that.

I'm not sure how the JSION deserialisation will work for these classes. The configs are fine since we control them. But the connections will be produced by Modelio. We will need to discuss the precise format at Stuttgart with Etienne.

For now, the project creation just creates empty lists for all these things :P

Let me know what you think.

### CODE REVIEW

**Comment by lausdahl** [comment]
Hi Luis,

Sounds good I will take a look once I finish the COE stuff which I ripped apart to run on the new configs and with UI.

For the Modelio stuff we need them to output the connections in the COE format as they do now + the FMU part which they do now but instead of a path they need to put some meaning full info from the model that can assist the user in selecting the right FMU file. So only a small change to what they have now.

**Comment by ldcouto** [comment]
So, we still want something like...
```json
"connections":{
 "{guid-controller}.instance1.valve":["{guid-tank}.
instance1.valve"],
 "{guid-tank}.instance1.level":["{guid-controller}.
instance1.level"]
 }
```

That one will be tricky to work with since it uses fields to define the first part of the connection. I think an array of string tuples would be easier to work with. How are you dealing with this in the COE?

**Comment by lausdahl** [comment]
Thats fine, already implemented all of that stuff, and Casper is creating a UI control to display it.

We use it like that in the COE, and is pretty easy to handle JSON in javascript/type script. Thats one thing that is easy, but guess thats where JSON started its life.

When I did the initial demo of the COE I wrote paring of the config.json used for the COE + for the livestream of data that the COE sends during simulation.

Now I have a class CoeConfig which can read all of the content in config.json either from one or multiple files depending on how go implement the final project layout.

**Comment by ldcouto** [comment]
Alright, but I think we'll lose type safety for the connections. We'll have to type them as `any`. Can I convince you to to for something like 

```json
"connections": [
  {"input":"{guid-controller}.instance1.valve","output":"{guid-tank}. instance1.valve"},
  {"input":"{guid-tank}.instance1.level","output":"{guid-controller}.instance1.level"}
]
```

instead? It would map nicely into something like
```typescript
interface Connection{
intput:string;
output:string
}

connections: Array<Connection>
```

which is still type safe. 

Or maybe we can treat the connections as a JSON literal? I would be ok with that too.

**Comment by lausdahl** [comment]
I dont want to change it. It is implemented in the COE and Modelio and my part of the app already. The COE checks this, we have type information for all of it inside the FMUs. So dont write any paring of these config files I already did that in the COE where it is needed.

I’m merging your stuff now, but could you give a heads up on renaming next time. Nothing could run since all paths was wrong after the merge. The html files also contains paths and I was restructuring the coe + casper did all the main/init and browser stuff which also had issues merging. I agree with your structure it would just have been easier if we coordinated it.

**Comment by ldcouto** [comment]
Ok, we can just treat it as a literal.

I'm sorry about the conflicts. When I opened the PR, everything was building correctly but Casper moved master. I emailed him to freeze it for a while. I have already started merging master in again but I can abort if you want to do it.

**Comment by lausdahl** [comment]
ok

I almost merged your stuff into my kel/createProject now and has our stuff running again (still needs to test the coe)

I think we should wait bit with more DOM stuff. I think I only need the Container you made and a new method on Project getChildren which I will write now that just returns all the children of the project.

I’m uncertain to how the getConfigs, getConmaps etc should be needed by the other parts of the app which cannot be handled by the container you did. It seems to have what is needed:
a type to identify it, essentially this says if it is a conman, config, …
a path to obtain the config if needed

Thats all we need from the COE point of view. The COE doesn’t need to get a DOM object of it as long as the format is defined. I mean the JSON. The config we have now can be parsed by CoeConfig it can consume all the config structures we have come up with so far and spit out what the COE needs.

**Comment by ldcouto** [comment]
Ok, so you're suggesting we just populate the views directly off the JSON files? I suppose that's fine.

I originally spit the DOM into Containers and non-containers since we would be interested in saving configs after the user changed them. I take your plan is to just implement the save feature directly in the CoeConfig?

`getConMaps` could be used to populate the connection map selector in the Co-Sim config view. I think it's better than iterating through the respective folder.  I can't think of a particular need for `getConfig` off the top of my head but one might come up. I think it's better to split the children getters by type than having a single getter and then having to iterate with if checks all the time.

**Comment by lausdahl** [comment]
> On 03 May 2016, at 22:13, Luis Diogo Couto <notifications@github.com> wrote:
> 
> Ok, so you're suggesting we just populate the views directly off the JSON files? I suppose that's fine.
> 
> Yes

> I originally spit the DOM into Containers and non-containers since we would be interested in saving configs after the user changed them. I take your plan is to just implement the save feature directly in the CoeConfig?
> 
> yes. You can then argue that the CoeConfig is the DOM and could be shared from the project. If so it has whats needed + a little more. Just wanted to be sure that you didn’t went ahead and implemented a duplicate of it. We other components needs parts of this I can split the class into parts that can parse and save sub elements of a config.
> getConMaps could be used to populate the connection map selector in the Co-Sim config view. I think it's better than iterating through the respective folder. I can't think of a particular need for getConfig off the top of my head but one might come up. I think it's better to split the children getters by type than having a single getter and then having to iterate with if checks all the time.
> 
> 
Thats where I think the user workflows can be simplified by changing the way we present everything in one file to 3 steps where the user during analysis probably only need to redo one step during analysis and not all of them. Here I refer to the user action required to:
export the conmap.
turn the conman into a multimodel, adding FMUs etc
and then finally performing analysis in the form of co-simulation. But I guess we can discuss the latter in person. Its a minor UI tweak that I think will make the workslow easier and give us less support.

**Comment by ldcouto** [comment]
I definitely don't think the COE should be the dom. It's a complete mixup
of responsibilities.

I would rather we have DOM classes that support read/write etc. It's
cleaner and easier for other views to use as well. We can refactor the the
code out of the CoeConfig class later.

When we discussed workflows, the connections map is one of the parameters
that can be varied in a configuration. So we need support for that.

 I think some of the things you want to clarify have already been
clarified. You were just on vacation ;)

**Comment by lausdahl** [comment]
> On 03 May 2016, at 22:35, Luis Diogo Couto <notifications@github.com> wrote:
> 
> I definitely don't think the COE should be the dom. It's a complete mixup
> of responsibilities.

I agree, I’m just saying that the implementation can be taken from here.
> 
> I would rather we have DOM classes that support read/write etc. It's
> cleaner and easier for other views to use as well. We can refactor the the
> code out of the CoeConfig class later.
> 
> When we discussed workflows, the connections map is one of the parameters
> that can be varied in a configuration. So we need support for that.
> 
> I think some of the things you want to clarify have already been
> clarified. You were just on vacation ;)

That may be, I just want it to be usable for us as well so we dont get all the support which we have now with the COE. But as I said probably better to talk about in person.

>

**Comment by ldcouto** [comment]
Right, just remember that app has to support more than the COE. I'm happy
to talk in person but we had originally planned to have the DOM finalized
and ready for Stuttgart. So I'm not wild about all this undefined stuff
before then.

**Comment by ldcouto** [comment]
Hmm, I just noticed the Co-Sim config tag has explicit Input/Output mappings. Why are we not using the connection mappings from Modelio? I'm pretty sure we agreed to supply a selector of exported mappings.

**Comment by lausdahl** [comment]
I dont under stand what you mean.

Not sure if this is what you talk about, but the configuration for a co-simulation will consist of 3 steps:

- 1. selection of conman
- 2. refine conman into a multimodel by adding specifying which FMUs that represents the different parts of the conmap + potential modification of parameters
- 3. addition of what ever is needed by the COE for a simulation e.g. start/end time, algorithm..

What is Co-Sim config tag?

**Comment by ldcouto** [comment]
Ok, then we are aligned.

But the Co-Sim view on `master` currently shows this:

screen shot 2016-05-03 at 22 56 14

**Comment by lausdahl** [comment]
yes we are working on this. Casper is building the controls and adding them to the coe page. I will when they work move them into the proper location and link it with the browser so it can be tried out. So we can see how it works in practise.

Note that the connections view initially will just be viewing the conmaps but we want it to be able to build them as well (as an advanced feature for us at AU, we might add a dev setting to enable this so the user doesn’t have the option by default if it in case it doesn’t align with the end user workflow)

**Comment by ldcouto** [comment]
Ok, makes sense. I've finished merging master with projdom. I can push it up.

I can't load settings or create projects but I'm not sure if 
a) the features are currently in master
b) it's some MacOs thing (all the new windows are empty)

**Comment by ldcouto** [comment]
projdom pushed. Kenneth, I leave it to you whether you want to merge or cherry-pick stuff. Just close the PR when you're done :)

**Comment by lausdahl** [comment]
they all work in my branch now.

I have your stuff and the project browser working with my structure

using this project here https://www.dropbox.com/s/rtfoyi7j1tq09za/test-create.zip?dl=0 <https://www.dropbox.com/s/rtfoyi7j1tq09za/test-create.zip?dl=0>

I haven’t got to the point where I managed to make the other structure you had work yet, need to branch of once I have all working.


The issue is that you moved the files around so everywhere where there is a path it needs fixing so it loads it from the correct location.

Also all require cannot have .ts, it must be without otherwise nested require doesn’t work once converted to .js. These are removed in my branch as well.

**Comment by ldcouto** [comment]
I fixed the paths in the references but maybe some got busted.

I'lll merge projdom with your branch. I'll also sort out the require ts. I didn't knowt hat,

**Comment by lausdahl** [comment]
sounds good.

I didn’t know about it either but Casper looked into that for me.

**Comment by ldcouto** [comment]
Alright, it's merged in ldc/dom-create-merge. That still needs to be merge into master

Still need to merge that into master but I'm having trouble figuring out the coe.ts file. Maybe one of you can take a look?

**Pull request merged**
