### PR TITLE
Added an option to define any number of graphs during a simulation

### PR DESCRIPTION
**Pull request by lausdahl**
Requested from #244 and IPP4CPPS

### CODE REVIEW

**Comment by ldcouto** [comment]
This is pretty good, but there are are some padding issues (see fig)

I think we should also disambiguate the Output log and Live graph config views with more explicit names.

How about ?
* Results Recording
* Live Plotting

untitled

**Comment by lausdahl** [comment]
Thats ok with me. Any idea on how to fix the padding.

**Comment by ldcouto** [comment]
Done.

**Comment by lausdahl** [comment]
Thanks

**Comment by ldcouto** [comment]
This is looking really good. A few quibbles:
* We have `Number of graph columns` and `Number of visible graph rows`. These seems like the same thing so we should delete visible for second.
* There's a `Graph Variables` label and text field. They are quite unaligned. And it's not clear what we are supposed to put there.

**Comment by lausdahl** [comment]
The visible rows is not the same as the number of columns. Columns is just as you expect the number of columns. The rows on the other hand is actually the number of rows that's visible in the current view area in the app, this is not the same as number of rows. Its just the number of rows you can see without scrolling.

Can you provide a little more info about the second issue I'm not sure what you mean here?

**Pull request merged**
