### PR TITLE
Add fmu export feature in the app for overture

### PR DESCRIPTION
**Pull request by lausdahl**
This adds the option to right click on a VDM Model folder in the app and export the FMU to the FMUs folder as either tool or source. It uses the fmu exporter cli which must be downloaded for.

I by mistake already added the overture.ts to master but also included it here.

### CODE REVIEW

**Comment by ldcouto** [comment]
This PR text makes no sense. Right-click an FMU and export it? I understand you mean model, but come on... spend at least 1 minute reading it  :)

Anyway, I'm not sure I like having an FMU exporter for a specific tool embedded in the app. Breaks balance and confuses users regarding the other tools. 

If you feel strongly about it, we can include it. But in that case, the messages need to be improved (error message is not user friendly and no confirmation message exists).

**Comment by lausdahl** [comment]
Sorry should have been VDM model folder. The request came from @pglvdm and @kgpierce I think to ease usage while used for teaching. So I guess it should be up to them if they really want this.

The error message should be the same as in Overture so now sure what you mean here?

Concerning confirmation are you thinking about a message box saying done when export is complete and no errors have occurred?

**Comment by pglvdm** [comment]
I can confirm that Ken Pierce and I would like this feature to be included for teaching purposes. Indeed it would be ideal if this was possible for all the baseline tools, and who knows when they see this it may also happen.

**Comment by ldcouto** [comment]
Alright, then let's get this in. Peter, when this is announced as a feature it would be a good opportunity to encourage other tool vendors to provide a similar capability :).

About the messages:

* if the CLI is not installed, we get this message: `Please install: overture-fmu-cli.jar first`. In the download manager, the tool is named `Overture FMU Import / Exporter CLI - Overture FMI Support`. We should make the names match.
* if there is an error in the export, it gives a message with `Errors:` and then the export. I'd suggest polishing the text to something like: `FMU Export Failed with Following Errors:`. 
* for the confirmation, a progress bar would be nicer. But if it's more pragmatic to go for a message box, that's fine too.
* Also, none of the message texts can be copied. It's not  a game-breaker but it's annoying for bug reports. If this is easy to address, would be good to do it.

**Comment by lausdahl** [comment]
I changed the interface into a window which shows everything the process prints so the user can see it all and copy the text. I changed the not installed name and the other points is removed since these dialogs on longer show.

image

is this ok or do you have any other suggestions.

**Comment by ldcouto** [comment]
I think it's very good now. Thanks.

I've merged it in.

**Pull request merged**
