### PR TITLE
This provides the ability to use a local downloaded update site

### PR DESCRIPTION
**Pull request by lausdahl**
This feature enabled the complete update site to be used from a local file system. The update site already contains a python script to generate a local version of the repo for use on USB sticks.

The implementation here enables support for the schema: `file:` where the previous implementation only supported `url:`.

The update should have no affect if the user doesn't enable it.

Related to findings at the summerschool: https://github.com/into-cps/intocps-ui/issues/244

### CODE REVIEW

**Comment by ldcouto** [comment]
I'm having a hard time testing this. The site creation script crashes for every version I've tried so far due to one tool or another having a broken download link.

In any case, this looks like a cool feature, but I suggest 2 enhancements
* use a file browser instead of a text field to locate the update site
* make it clear (perhaps in the label) what exactly should be chosen for the update site. versions.json? root folder?

**Comment by lausdahl** [comment]
I agree with both enhancements but I think this is a general enhancement and not just for this tool. Every tool setting needs a help text and we need to enable the file/ directory select dialog when needed its annoying to try and copy past a path.

So we could rais such an issue as an enhancement.

For the script did you use the `master` branch? I think I updated the `development` branch to handle timeouts. But its a constant issue that at least 1-3 of the tools are offline or the md5 checksum fails.

**Comment by ldcouto** [comment]
Ya, fair points on the enhancements. I'll open the issue.

I tried master, yeah. Will try dev later today. If the script can handle missing DLs and chesums should be good to go. To complete the testing, can you just tell me what I should pick as the path for the local repo?

**Comment by lausdahl** [comment]
Like this (same style as the online repos): 
image

**Comment by ldcouto** [comment]
Working well now. I'm ok to merge this in, but we are already in RC so let's do it at the next release instead.

**Pull request merged**
