### PR TITLE
added the ability to set a filter on live streaming so values only wi…

### PR DESCRIPTION
**Pull request by lausdahl**
This adds the ability to filter live log values bases on this. This is handy when running with small step sizes since it almost kills the app to draw the graph

### CODE REVIEW

**Comment by lausdahl** [comment]
You need the latest COE 0.1.13-SNAPSHOT

**Comment by ldcouto** [comment]
Does this crash with prior versions of the COE?

**Comment by lausdahl** [comment]
yes this is not backwards compatible. I changed the COE to not require all properties in the future

**Comment by ldcouto** [comment]
If it's not backwards-compatible, we need to bump the app to 3.0.0.

Other than that, I'm fine with this.

**Pull request merged**
