### PR TITLE
New COE Interface

### PR DESCRIPTION
**Pull request by lausdahl**
This contains a new COE interface and new view for showing the COE console output + log file, and a space for the traceability daemon.

The new interface allows the COE to keep running in the background even when the app is terminated. On app restart the log and console.log are reconnected to the view and preloaded with a slice of history. However to have the console output become live again the COE must be restarted (this is not needed in most cases since the log shows nearly the same information)

I tested the implementation on windows and mac and it looks nearly the same and works in the same way.

I need some help improving the code since one of the files contains CSS style which I believe should be in a CSS file somewhere.

is also changed the project browser to load async.

### CODE REVIEW

**Comment by CThuleHansen** [comment]
Hey @ldcouto , we have carried out additional work on the issues. Could you take a look at it?

**Comment by ldcouto** [comment]
Looking good.

A few notes...

* It's not very obvious what the stream redirect label and icon are supposed to be. I guess it's reconnecting to prior COEs. Maybe we can rename them?
* The status and log viws do not pick up externally launched COEs (see figure)
* The status page also shows the log
* Should we we use Online/Offline instead of cross/tick? Might be more intuitive
* The stream redirect does not pick up COEs launched from previous app runs. But the log does :)

coe-status


coe-log

**Comment by CThuleHansen** [comment]
@ldcouto few answers:
* It's not very obvious what the stream redirect label and icon are supposed to be. I guess it's reconnecting to prior COEs. Maybe we can rename them?
**COE Status will be changed to COE Console.
We will add some mouse-over text describing "Stream Redirect"**
* The status and log viws do not pick up externally launched COEs (see figure)
**The log view connects to the coe.log file located in "into-cps-projects\install\coe-working-dir". It works externally, if piped into this file. The COE Status connects to the process running the COE. If this is from an earlier run, then a relaunch must be performed.**
* The status page also shows the log
**This will be changed with next release of the COE**
* Should we we use Online/Offline instead of cross/tick? Might be more intuitive
**We'll add some new icons**
* The stream redirect does not pick up COEs launched from previous app runs. But the log does :)
**See bulletin 2 answer**

**Comment by ldcouto** [comment]
"The log view connects to the coe.log file located in "into-cps-projects\install\coe-working-dir". It works externally, if piped into this file. The COE Status connects to the process running the COE. If this is from an earlier run, then a relaunch must be performed."

What does relaunch mean in this case?

**Comment by CThuleHansen** [comment]
Press stop and launch

**Comment by ldcouto** [comment]
Gotcha.

We need to be sure we document this feature. There's potential for a bit of confusion for the COE connections, etc. tagging @bandurvp so he tracks this as well.

**Comment by CThuleHansen** [comment]
Ready to merge @ldcouto ! :)

**Comment by ldcouto** [comment]
I'm finding a lot more trouble this time.

The coe console launches the coe  from `install_downloads`. The log picks it up from `install`. This causes obvious problems

The launcher has other problems. If there is no coe in `install_downloads`, it throws some ugly errors.

Eventually it launches off some other path, but the console command is still shown as `Terminal args: java -jar C:\Users\CoutoLD\Documents\into-cps-projects\install_downloads\coe.jar`

But none of my co-simulations go past 0% and no logs are generated, so something is wrong.

Any ideas what could be causing this? I put the coe in `install`, even deleted it from `install_dir`, but that just causes the launch to fail. By the way, if the launcher fails, it's quite ungraceful -- just hangs there. Should

At first I thought something was wrong with my settings but my `install_dir` is `install`

I'll do more extensive testing tomorrow.

**Comment by ldcouto** [comment]
Screenshot of error

untitled

**Comment by lausdahl** [comment]
I just pushed a change so it always runs from `install_downloads`

I think you have some none default settings somewhere to get that error. Did you set a custom path for the COE maybe?


* not sure what the issue is with the logs in a different place than the COE but I changed it to be the same root folder now
* if there is no coe in install downloads then I get a message saying that I should install it
* do you know why no progress is being made. I mean is it related to this change? Maybe try enabling trace on the coe

**Comment by ldcouto** [comment]
I nuked my settings so everything was in defaults.

I've sorted out the co-simulation launching. Took a while to identify. If the `coe_working_dir` folder does not exist when the coe is launched, then the console and the log do not connect properly. If you launch a co-simulation, nothing happens (stays at 0% -- see attached)

If you kill and relaunch the coe, the console will connect. But the log will not. You have to relaunch the app for the log to get picked up.

If this is error is easy to fix, let's do it. Otherwise, it's a relatively simple workaround to relaunch the coe and retstart the app. This only has to be done once.

Also, all the code for this feature is in the root of `src` ? Can you move it to a dedicated folder like the other components?


untitled

**Comment by lausdahl** [comment]
I added a check and created the folder if the path is obtained

**Comment by ldcouto** [comment]
Working perfectly now.

**Pull request merged**
