### PR TITLE
enable simple markdown readme.md to be shown on project open if the file exists in the root

### PR DESCRIPTION
**Pull request by lausdahl**
This is a simple implementation that shows readme.md on the main page on project open. It can handle markdown images as well (when the picture is relative to the root of the repo). The main issue is that users cannot see the description of the casestudies when they open them in the app. Issue is raised in #244

### CODE REVIEW

**Comment by ldcouto** [comment]
Is this a revised version of #256 ?

As before, I'm worried about the capitalization of "Readme.md" on linux systems

**Comment by lausdahl** [comment]
yes

good point with the `Readme.md` it seems to regencies any version on mac but not sure if this is mac or electron that enables this. I think a linux test is needed. However, if not matched it simply ignores the feature, so if you think it is ok as a first implementation we could pull it in.

**Comment by ldcouto** [comment]
Yeah, that's fine by me.

Is there anyone at AU that can do a quick check on Linux? Maybe Victor or Hugo?

**Comment by lausdahl** [comment]
@bandurvp @idhugo can any of you check this on Linux. Does this still show the readme if spelled with different capitalisation:  REadme.md, ReAdMe.md, Readme.MD etc.

**Comment by bandurvp** [comment]
Guys, I'm on branch au/readme and I've tried to open some of the case studies.  All have a file named "README.md", with that capitalization.  When I populate the file with some text the main app window does not display anything.  If I rename it to "readme.md" it also displays nothing.  Is this the test you had in mind?

Victor

**Comment by ldcouto** [comment]
Yeah. And the results are consistent with what I'd expect.

Can you change the code so that it tries to open the following 3 variations?

1. README.MD
2. Readme.md
3. readme.md

**Comment by lausdahl** [comment]
Can you try with a file named: Readme.md

just to make sure that the rest of the code works as intended.

Regards,

Kenneth Lausdahl
kenneth@lausdahl.com

**Comment by bandurvp** [comment]
I can confirm that it works when the file is named "Readme.md" but nothing else.  I'll

Victor

**Comment by bandurvp** [comment]
Hi guys,

I've pushed a change to the branch au/readme that checks for files with four different capitalizations:  readme.md, Readme.md, README.MD and README.md.

Victor

**Comment by lausdahl** [comment]
ok I will merge it then since Luis already approved it.

**Pull request merged**
